import { ClientEvent as ClientSideEvent } from "@shared/game/network/model/event/client-event";

export enum AttackType {
  HOLE_1,
}

export interface Attack {
  type: AttackType;
  power: number;
}

export interface AttackDistribution {
  playerIndex: number;
  attacks: Attack[];
}

// ServerSideEvents are generated by server player and should only be handled by local player,
//  remote players will handle these events on acknowledgement instead.
export interface ServerSideEvent {
  attackDistributions?: AttackDistribution[];
}

export interface ServerPlayerEvent {
  playerIndex: number,
  clientEvent?: ClientSideEvent,
  serverEvent?: ServerSideEvent,
}

export interface ServerEvent {
  roomId: number;
  playerEvents: ServerPlayerEvent[];
}
