import { AttackDistribution } from "@shared/game/network/model/attack/attack-distribution";
import { ClientEvent as ClientSideEvent } from "@shared/game/network/model/event/client-event";

// ServerSideEvents are generated by server player and should only be handled by local player,
//  remote players will handle these events on acknowledgement instead.
export interface ServerSideEvent {
  attackDistributions?: AttackDistribution[];
}

export interface ServerPlayerEvent {
  playerIndex: number,
  clientEvent?: ClientSideEvent,
  serverEvent?: ServerSideEvent,
}

export interface ServerEvent {
  roomId: number;
  playerEvents: ServerPlayerEvent[];
}
