import { ClientEvent } from "@shared/game/network/model/event/client-event";

export interface GarbageDistribution {
  playerIndex: number;
  attackPower: number[];
}

export interface ServerPlayerEvent {
  playerIndex: number,
  clientEvent: ClientEvent
  
  // the garbage here is generated by server player and should only be handled by local player,
  //  remote players will handle garbage on acknowledgement instead.
  garbageDistribution?: GarbageDistribution[];
}

export interface ServerEvent {
  roomId: number;
  playerEvents: ServerPlayerEvent[];
}
