/**
 * Cultris 3
 * REST API provided by the C3 Main Server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DebugResponseDto { 
    /**
     * This is where the client can connect to the game server via websocket.
     */
    gameServerUrl: string;
    debugMessage: string;
}

